spring:
  application:
    name: microservicio-gateway
  cloud:
    gateway:
      routes:
      - id: microservicio-usuarios
        uri: lb://microservicio-usuarios
        predicates: 
        - Path=/api/alumnos/**
        filters:
        - StripPrefix=2
      - id: microservicio-cursos
        uri: lb://microservicio-cursos
        predicates: 
        - Path=/api/cursos/**
        filters:
        - StripPrefix=2
      - id: microservicio-examenes
        uri: lb://microservicio-examenes
        predicates: 
        - Path=/api/examenes/**
        filters:
        - StripPrefix=2
      - id: microservicio-respuestas
        uri: lb://microservicio-respuestas
        predicates: 
        - Path=/api/respuestas/**
        filters:
        - StripPrefix=2
    loadbalancer:
      ribbon:
        enabled: false
        
server:
  port: 7000
  
eureka:                  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
